### ISSUE TITLE
No module named 'gql.transport.http'

### ISSUE THREAD

**Issue by antoine4ucsd** [Wei-Shao/HIV-DRLink#1]
hello
I am trying to use your code but get an error
I installed sierrapy, and the addotinoal packages
```
pip install --pre gql[aiohttp]
pip install --pre gql[aiohttp]
```
but still get the same error
```
sierrapy fasta baseline_selected.fasta -g simple_mutations.gql  -o output.json
Traceback (most recent call last):
  File "/mypath/bin/sierrapy", line 6, in <module>
    from sierrapy.cmds import main
  File "/mypath/lib/python3.10/site-packages/sierrapy/__init__.py", line 2, in <module>
    from .sierraclient import VERSION, SierraClient
  File "/mypath/lib/python3.10/site-packages/sierrapy/sierraclient.py", line 8, in <module>
    from gql.transport.http import HTTPTransport
ModuleNotFoundError: No module named 'gql.transport.http'
```

any suggestions?

sierrapy seems properly installed
```
pip install sierrapy
Requirement already satisfied: sierrapy in /mypath/lib/python3.10/site-packages (0.2.1)
Requirement already satisfied: six>=1.10.0 in /mypath/lib/python3.10/site-packages (from sierrapy) (1.16.0)
Requirement already satisfied: voluptuous>=0.10.5 in /mypath/lib/python3.10/site-packages (from sierrapy) (0.13.1)
Requirement already satisfied: graphql-core>=0.5.3 in /mypath/lib/python3.10/site-packages (from sierrapy) (2.3.2)
Requirement already satisfied: tqdm>=4.8.4 in /mypath/lib/python3.10/site-packages (from sierrapy) (4.64.0)
Requirement already satisfied: click>=6.7 in /mypath/lib/python3.10/site-packages (from sierrapy) (8.0.4)
Requirement already satisfied: requests>=2.11.1 in /mypath/lib/python3.10/site-packages (from sierrapy) (2.27.1)
Requirement already satisfied: promise>=0.4.2 in /mypath/lib/python3.10/site-packages (from sierrapy) (2.3)
Requirement already satisfied: gql>=0.1.0 in /mypath/lib/python3.10/site-packages (from sierrapy) (2.0.0)
Requirement already satisfied: rx<2,>=1.6 in /mypath/lib/python3.10/site-packages (from graphql-core>=0.5.3->sierrapy) (1.6.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /mypath/lib/python3.10/site-packages (from requests>=2.11.1->sierrapy) (1.26.11)
Requirement already satisfied: idna<4,>=2.5 in /mypath/lib/python3.10/site-packages (from requests>=2.11.1->sierrapy) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /mypath/lib/python3.10/site-packages (from requests>=2.11.1->sierrapy) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /mypath/lib/python3.10/site-packages (from requests>=2.11.1->sierrapy) (2022.9.24)
```

thank you!

**Comment by Wei-Shao** [comment]
Hello,
That is probably an environment issue. Please check the first line of sierrapy to see if the python library is same as the one you installed
Wei

From: antoine ***@***.***>
Sent: Wednesday, September 28, 2022 8:12 PM
To: Wei-Shao/HIV-DRLink ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [Wei-Shao/HIV-DRLink] No module named 'gql.transport.http' (Issue #1)


hello
I am trying to use your code but get an error
I installed sierrapy, and the addotinoal packages

pip install --pre gql[aiohttp]

pip install --pre gql[aiohttp]

but still get the same error

sierrapy fasta baseline_selected.fasta -g simple_mutations.gql  -o output.json

Traceback (most recent call last):

  File "/mypath/bin/sierrapy", line 6, in <module>

    from sierrapy.cmds import main

  File "/mypath/lib/python3.10/site-packages/sierrapy/__init__.py", line 2, in <module>

    from .sierraclient import VERSION, SierraClient

  File "/mypath/lib/python3.10/site-packages/sierrapy/sierraclient.py", line 8, in <module>

    from gql.transport.http import HTTPTransport

ModuleNotFoundError: No module named 'gql.transport.http'

any suggestions?

sierrapy seems properly installed

pip install sierrapy

Requirement already satisfied: sierrapy in /mypath/lib/python3.10/site-packages (0.2.1)

Requirement already satisfied: six>=1.10.0 in /mypath/lib/python3.10/site-packages (from sierrapy) (1.16.0)

Requirement already satisfied: voluptuous>=0.10.5 in /mypath/lib/python3.10/site-packages (from sierrapy) (0.13.1)

Requirement already satisfied: graphql-core>=0.5.3 in /mypath/lib/python3.10/site-packages (from sierrapy) (2.3.2)

Requirement already satisfied: tqdm>=4.8.4 in /mypath/lib/python3.10/site-packages (from sierrapy) (4.64.0)

Requirement already satisfied: click>=6.7 in /mypath/lib/python3.10/site-packages (from sierrapy) (8.0.4)

Requirement already satisfied: requests>=2.11.1 in /mypath/lib/python3.10/site-packages (from sierrapy) (2.27.1)

Requirement already satisfied: promise>=0.4.2 in /mypath/lib/python3.10/site-packages (from sierrapy) (2.3)

Requirement already satisfied: gql>=0.1.0 in /mypath/lib/python3.10/site-packages (from sierrapy) (2.0.0)

Requirement already satisfied: rx<2,>=1.6 in /mypath/lib/python3.10/site-packages (from graphql-core>=0.5.3->sierrapy) (1.6.1)

Requirement already satisfied: urllib3<1.27,>=1.21.1 in /mypath/lib/python3.10/site-packages (from requests>=2.11.1->sierrapy) (1.26.11)

Requirement already satisfied: idna<4,>=2.5 in /mypath/lib/python3.10/site-packages (from requests>=2.11.1->sierrapy) (3.3)

Requirement already satisfied: charset-normalizer~=2.0.0 in /mypath/lib/python3.10/site-packages (from requests>=2.11.1->sierrapy) (2.0.4)

Requirement already satisfied: certifi>=2017.4.17 in /mypath/lib/python3.10/site-packages (from requests>=2.11.1->sierrapy) (2022.9.24)

thank you!

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWei-Shao%2FHIV-DRLink%2Fissues%2F1&data=05%7C01%7Cshaow%40mail.nih.gov%7C8a44733cfc79426a4c4a08daa1af4539%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638000071395370912%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0vdkDYrKDvROzplJp1aT2mo%2FQB20R3cW7PU4p48lKYI%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAENX3NY6KVKZK6X5Y73Q6Q3WATNELANCNFSM6AAAAAAQYIM2PU&data=05%7C01%7Cshaow%40mail.nih.gov%7C8a44733cfc79426a4c4a08daa1af4539%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638000071395370912%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GRF3XYuC1OXhVbK8y9Bk2%2BOyfw4m8i%2BNd5CeNkX%2BDPw%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.******@***.***>>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by antoine4ucsd** [comment]
thank you 
I built a conda env with default python (3.10.4)
sierrapy is version 0.2.1

```
# -*- coding: utf-8 -*-

from collections import OrderedDict

import requests
from tqdm import tqdm
from gql import gql, Client
from gql.transport.http import HTTPTransport
from graphql.execution import ExecutionResult
from graphql.language.printer import print_ast
from requests.exceptions import HTTPError

VERSION = '0.2.1'
DEFAULT_URL = 'https://hivdb.stanford.edu/graphql'

```
I can create a new env with an older version of python if you think this could do the trick
thank you

**Comment by Wei-Shao** [comment]
Can you run "which python" to see what is the default python you are using and then check the first line of the sierrapy you installed?

From: antoine ***@***.***>
Sent: Friday, September 30, 2022 10:46 AM
To: Wei-Shao/HIV-DRLink ***@***.***>
Cc: Shao, Wei (NIH/NCI) [C] ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [Wei-Shao/HIV-DRLink] No module named 'gql.transport.http' (Issue #1)


thank you
I built a conda env with default python (3.10.4)
sierrapy is version 0.2.1

# -*- coding: utf-8 -*-



from collections import OrderedDict



import requests

from tqdm import tqdm

from gql import gql, Client

from gql.transport.http import HTTPTransport

from graphql.execution import ExecutionResult

from graphql.language.printer import print_ast

from requests.exceptions import HTTPError



VERSION = '0.2.1'

DEFAULT_URL = 'https://hivdb.stanford.edu/graphql'



I can create a new env with an older version of python if you think this could do the trick
thank you

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWei-Shao%2FHIV-DRLink%2Fissues%2F1%23issuecomment-1263670110&data=05%7C01%7Cshaow%40mail.nih.gov%7C601aeb3934fd47a0e36b08daa2f27885%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638001459550421492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lEZBsnW5v5ZMKI%2FlmzHtWNV2pf7wcTAt6EB5JnH1vpE%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAENX3N7BJFHQKJBJUNQXTETWA34J3ANCNFSM6AAAAAAQYIM2PU&data=05%7C01%7Cshaow%40mail.nih.gov%7C601aeb3934fd47a0e36b08daa2f27885%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638001459550421492%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Vi%2FFhvtuA%2BPkLwnJprYdRE6OzjY167zK7aImMfTAZ30%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.******@***.***>>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by antoine4ucsd** [comment]
I am using 
Python 3.10.4
my env is below
```
# Name                    Version                   Build  Channel
aiohttp                   3.7.4.post0              pypi_0    pypi
aiohttp-graphql           1.1.0              pyh9f0ad1d_0    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
async-timeout             3.0.1                    pypi_0    pypi
attrs                     22.1.0             pyh71513ae_1    conda-forge
backoff                   2.1.2              pyhd8ed1ab_0    conda-forge
botocore                  1.27.82                  pypi_0    pypi
brotlipy                  0.7.0           py310hca72f7f_1002  
bzip2                     1.0.8                h1de35cc_0  
ca-certificates           2022.9.24            h033912b_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310hc55c11b_0  
chardet                   4.0.0                    pypi_0    pypi
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4           py310hecd8cb5_0  
cryptography              37.0.1          py310hf6deb26_0  
frozenlist                1.3.1           py310h3c08dca_0    conda-forge
gql                       2.0.0              pyh9f0ad1d_0    conda-forge
graphql-core              2.3.2              pyh9f0ad1d_0    conda-forge
graphql-server-core       1.2.0                      py_1    conda-forge
idna                      3.3                pyhd3eb1b0_0  
jmespath                  1.0.1                    pypi_0    pypi
libcxx                    14.0.6               h9765a3e_0  
libffi                    3.3                  hb1e8313_2  
multidict                 5.2.0           py310hca72f7f_3  
ncurses                   6.3                  hca72f7f_3  
openssl                   1.1.1q               hfe4f2af_0    conda-forge
pip                       22.1.2          py310hecd8cb5_0  
promise                   2.3             py310hecd8cb5_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pysocks                   1.7.1           py310hecd8cb5_0  
python                    3.10.4               hdfd78df_0  
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1.2                hca72f7f_1  
requests                  2.27.1             pyhd3eb1b0_0    anaconda
requests-toolbelt         0.9.1                    pypi_0    pypi
rx                        1.6.1                      py_0    conda-forge
setuptools                63.4.1          py310hecd8cb5_0  
sierrapy                  0.2.1                      py_2    bioconda
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.39.2               h707629a_0  
tk                        8.6.12               h5d9f67b_0  
tqdm                      4.64.0          py310hecd8cb5_0  
typing-extensions         4.3.0           py310hecd8cb5_0  
typing_extensions         4.3.0           py310hecd8cb5_0  
tzdata                    2022c                h04d1e81_0  
urllib3                   1.26.11         py310hecd8cb5_0  
voluptuous                0.13.1             pyhd8ed1ab_0    conda-forge
websockets                10.3                     pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.6                hca72f7f_0  
yarl                      1.8.1           py310hca72f7f_0  
zlib                      1.2.12               h4dc903c_3  

```

**Comment by antoine4ucsd** [comment]
I created a new env and installed the dev version of sierrapy. now it works but only without the -g option.
```
sierrapy fasta -g simple_mutations.gql -o output.json baseline_renamed.fas
Usage: sierrapy fasta [OPTIONS] FASTA...
```
but this works:
```
sierrapy fasta -o output.json baseline_renamed.fas
641it [02:15,  4.51it/s]

```
it results in multiple json outputs like the one attached
[output.0.json.zip](https://github.com/Wei-Shao/HIV-DRLink/files/9686018/output.0.json.zip)

next I tried this

```
HIV-DRLink_github.pl output.0.json
Can't use an undefined value as an ARRAY reference at HIV-DRLink_github.pl line 97.
```
sorry if I am missing something obvious here.

**Comment by antoine4ucsd** [comment]
the -q argument (instead of -g) works but generates multiple outputs - I guess it processes sequences in small batches. 
can the entire alignment be processed and one ouput be generated?
```
sierrapy fasta -q  simple_mutations.gql  -o output.json baseline_renamed.fas

```
then this works

```
HIV-DRLink_github.pl output.0.json
```

**Comment by Wei-Shao** [comment]
It should generate only one output file per input fasta file. I'll take a look later.
Right,  "-q" and "-g" can be confusing.

From: antoine ***@***.***>
Sent: Friday, September 30, 2022 12:20 PM
To: Wei-Shao/HIV-DRLink ***@***.***>
Cc: Shao, Wei (NIH/NCI) [C] ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [Wei-Shao/HIV-DRLink] No module named 'gql.transport.http' (Issue #1)


the -q argument (instead of -g) works but generates multiple outputs - I guess it processes sequences in small batches.
can the entire alignment be processed and one ouput be generated?

sierrapy fasta -q  simple_mutations.gql  -o output.json baseline_renamed.fas



then this works

HIV-DRLink_github.pl output.0.json

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWei-Shao%2FHIV-DRLink%2Fissues%2F1%23issuecomment-1263770797&data=05%7C01%7Cshaow%40mail.nih.gov%7C3c7bdd2de12f488d915608daa2ffa573%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638001516123186485%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oGhsekRI5QsXYDPFwo%2BYo9%2FNUoHaGK67hA1HLPdbYfA%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAENX3N5OAXIS47JI2OVUVOTWA4HLFANCNFSM6AAAAAAQYIM2PU&data=05%7C01%7Cshaow%40mail.nih.gov%7C3c7bdd2de12f488d915608daa2ffa573%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638001516123186485%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mjom8ZAPk6RkjA6q%2BgrUOdTN7bgedOTBWUR5D7Ou7Do%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.******@***.***>>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by antoine4ucsd** [comment]
thank you (for now, it generate output from 0 to 12)

**Comment by Wei-Shao** [comment]
That is strange.

From: antoine ***@***.***>
Sent: Friday, September 30, 2022 12:30 PM
To: Wei-Shao/HIV-DRLink ***@***.***>
Cc: Shao, Wei (NIH/NCI) [C] ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [Wei-Shao/HIV-DRLink] No module named 'gql.transport.http' (Issue #1)


thank you (for now, it generate output from 0 to 12)

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWei-Shao%2FHIV-DRLink%2Fissues%2F1%23issuecomment-1263781055&data=05%7C01%7Cshaow%40mail.nih.gov%7Cc3c12fb4e3e34130692008daa3010f92%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638001522195894733%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=z6G56rQ%2BWY0XiePENl8%2BVV0Wbp8nRDw1pXuSr4Ca%2FVg%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAENX3NZN53OSUZWLUU3JF23WA4IRNANCNFSM6AAAAAAQYIM2PU&data=05%7C01%7Cshaow%40mail.nih.gov%7Cc3c12fb4e3e34130692008daa3010f92%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638001522195894733%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=US8YnrahJPIEs%2FfssVhaPaOQ%2Bvh7TxsPOSLDyUCzc3k%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.******@***.***>>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by Wei-Shao** [comment]
Hello,
I tested a fasta file that had 5000 sequences. It worked fine. The script produced only one json file.
By the way, the command in your email "sierrapy fasta -q  simple_mutations.gql  -o output.json baseline_renamed.fas" should be "sierrapy fasta baseline_renamed.fas -q  simple_mutations.gql  -o output.json (or -o baseline_renamed.json)".
If you still have problem running sierrapy, you may contact Philip Tzou ***@***.******@***.***> who is in charge of sierrapy.

From: antoine ***@***.***>
Sent: Friday, September 30, 2022 12:20 PM
To: Wei-Shao/HIV-DRLink ***@***.***>
Cc: Shao, Wei (NIH/NCI) [C] ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [Wei-Shao/HIV-DRLink] No module named 'gql.transport.http' (Issue #1)


the -q argument (instead of -g) works but generates multiple outputs - I guess it processes sequences in small batches.
can the entire alignment be processed and one ouput be generated?

sierrapy fasta -q  simple_mutations.gql  -o output.json baseline_renamed.fas



then this works

HIV-DRLink_github.pl output.0.json

-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWei-Shao%2FHIV-DRLink%2Fissues%2F1%23issuecomment-1263770797&data=05%7C01%7Cshaow%40mail.nih.gov%7C3c7bdd2de12f488d915608daa2ffa573%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638001516123186485%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oGhsekRI5QsXYDPFwo%2BYo9%2FNUoHaGK67hA1HLPdbYfA%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAENX3N5OAXIS47JI2OVUVOTWA4HLFANCNFSM6AAAAAAQYIM2PU&data=05%7C01%7Cshaow%40mail.nih.gov%7C3c7bdd2de12f488d915608daa2ffa573%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638001516123186485%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mjom8ZAPk6RkjA6q%2BgrUOdTN7bgedOTBWUR5D7Ou7Do%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.******@***.***>>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by antoine4ucsd** [comment]
thank you for getting back to me. I will give it another try with your cmd line and let you know if I still have the same issue,

**Comment by Wei-Shao** [comment]
How about the first line of sierrapy?

From: antoine ***@***.***>
Sent: Friday, September 30, 2022 11:18 AM
To: Wei-Shao/HIV-DRLink ***@***.***>
Cc: Shao, Wei (NIH/NCI) [C] ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [Wei-Shao/HIV-DRLink] No module named 'gql.transport.http' (Issue #1)


I am using
Python 3.10.4
my env is below

# Name                    Version                   Build  Channel

aiohttp                   3.7.4.post0              pypi_0    pypi

aiohttp-graphql           1.1.0              pyh9f0ad1d_0    conda-forge

aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge

async-timeout             3.0.1                    pypi_0    pypi

attrs                     22.1.0             pyh71513ae_1    conda-forge

backoff                   2.1.2              pyhd8ed1ab_0    conda-forge

botocore                  1.27.82                  pypi_0    pypi

brotlipy                  0.7.0           py310hca72f7f_1002

bzip2                     1.0.8                h1de35cc_0

ca-certificates           2022.9.24            h033912b_0    conda-forge

certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge

cffi                      1.15.1          py310hc55c11b_0

chardet                   4.0.0                    pypi_0    pypi

charset-normalizer        2.0.4              pyhd3eb1b0_0

click                     8.0.4           py310hecd8cb5_0

cryptography              37.0.1          py310hf6deb26_0

frozenlist                1.3.1           py310h3c08dca_0    conda-forge

gql                       2.0.0              pyh9f0ad1d_0    conda-forge

graphql-core              2.3.2              pyh9f0ad1d_0    conda-forge

graphql-server-core       1.2.0                      py_1    conda-forge

idna                      3.3                pyhd3eb1b0_0

jmespath                  1.0.1                    pypi_0    pypi

libcxx                    14.0.6               h9765a3e_0

libffi                    3.3                  hb1e8313_2

multidict                 5.2.0           py310hca72f7f_3

ncurses                   6.3                  hca72f7f_3

openssl                   1.1.1q               hfe4f2af_0    conda-forge

pip                       22.1.2          py310hecd8cb5_0

promise                   2.3             py310hecd8cb5_0

pycparser                 2.21               pyhd3eb1b0_0

pyopenssl                 22.0.0             pyhd3eb1b0_0

pysocks                   1.7.1           py310hecd8cb5_0

python                    3.10.4               hdfd78df_0

python-dateutil           2.8.2                    pypi_0    pypi

python_abi                3.10                    2_cp310    conda-forge

readline                  8.1.2                hca72f7f_1

requests                  2.27.1             pyhd3eb1b0_0    anaconda

requests-toolbelt         0.9.1                    pypi_0    pypi

rx                        1.6.1                      py_0    conda-forge

setuptools                63.4.1          py310hecd8cb5_0

sierrapy                  0.2.1                      py_2    bioconda

six                       1.16.0             pyhd3eb1b0_1

sqlite                    3.39.2               h707629a_0

tk                        8.6.12               h5d9f67b_0

tqdm                      4.64.0          py310hecd8cb5_0

typing-extensions         4.3.0           py310hecd8cb5_0

typing_extensions         4.3.0           py310hecd8cb5_0

tzdata                    2022c                h04d1e81_0

urllib3                   1.26.11         py310hecd8cb5_0

voluptuous                0.13.1             pyhd8ed1ab_0    conda-forge

websockets                10.3                     pypi_0    pypi

wheel                     0.37.1             pyhd3eb1b0_0

xz                        5.2.6                hca72f7f_0

yarl                      1.8.1           py310hca72f7f_0

zlib                      1.2.12               h4dc903c_3



-
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FWei-Shao%2FHIV-DRLink%2Fissues%2F1%23issuecomment-1263706960&data=05%7C01%7Cshaow%40mail.nih.gov%7Ce716a9218a0144608fde08daa2f6e9ce%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638001478617025873%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PlImD5CLGFS6Zpsn%2BRY2JWoo13tpisahbOjWhCyXwi8%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAENX3NYYQT3WXBOGL6LWLF3WA4ABDANCNFSM6AAAAAAQYIM2PU&data=05%7C01%7Cshaow%40mail.nih.gov%7Ce716a9218a0144608fde08daa2f6e9ce%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638001478617025873%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=js3%2B8iXC4B4QkzhbgEBlAY%2F8g0tGCCrGszo1%2B5k%2FOQg%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.******@***.***>>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.
